import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import YAML from "yaml";
import piScholarExtension from "../src/index.js";
import { archive, json } from "./helpers.js";

const raw=(key:string,itemType:string,data:Record<string,unknown>={},version=1)=>({key,version,data:{itemType,...data}});
function tools(){const values:any[]=[];piScholarExtension({registerTool:(x:any)=>values.push(x),registerCommand:()=>{},on:()=>{},getAllTools:()=>values,getActiveTools:()=>[],setActiveTools:()=>{},sendUserMessage:()=>{}} as any);return new Map(values.map(x=>[x.name,x]));}
function setEnv(t:test.TestContext,values:Record<string,string>){const old=new Map<string,string|undefined>();for(const [k,v] of Object.entries(values)){old.set(k,process.env[k]);process.env[k]=v;}t.after(()=>{for(const [k,v] of old)v===undefined?delete process.env[k]:process.env[k]=v;});}
function zoteroFixture(url:URL,pdf:string):Response|null{const parent=raw("PARENT01","journalArticle",{title:"Structured Research",creators:[{creatorType:"author",firstName:"Ada",lastName:"Lovelace"}],date:"2024",DOI:"10.1000/mock",ISBN:"978-x",ISSN:"1234",publicationTitle:"Journal",volume:"1",issue:"2",pages:"3-9",url:"https://paper.example",abstractNote:"Abstract",tags:[{tag:"mock"}],collections:["COLL0001"]},20);if(url.pathname.endsWith("/items/PARENT01"))return json(parent);if(url.pathname.endsWith("/items/PARENT01/children"))return json([raw("NOTE0001","note",{parentItem:"PARENT01",note:"A note"}),raw("PDF00001","attachment",{parentItem:"PARENT01",title:"PDF",filename:"paper.pdf",contentType:"application/pdf",linkMode:"linked_file",path:pdf}),raw("SUPP0001","attachment",{parentItem:"PARENT01",title:"Supplement",filename:"supp.pdf",contentType:"application/pdf",linkMode:"linked_file",path:pdf})]);if(url.pathname.endsWith("/collections"))return json([raw("COLL0001","collection",{name:"Collection"})]);if(url.pathname.endsWith("/items/PDF00001/children"))return json([raw("ANNO0001","annotation",{parentItem:"PDF00001",annotationText:"finding",annotationComment:"important",annotationPageLabel:"1",annotationPosition:{pageIndex:0}})]);if(url.pathname.endsWith("/items/SUPP0001/children"))return json([]);if(url.pathname.includes("/file/view/url"))return new Response(pathToFileURL(pdf).href);if(url.pathname.includes("/fulltext"))return url.pathname.includes("PDF00001")?json({content:"indexed body",indexedPages:1,totalPages:1}):new Response("missing",{status:404});return null;}

test("mocked success E2E maps Zotero Paper, uploads/polls MinerU and publishes complete Markdown/YAML/assets",async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),"pi-scholar-e2e-"));const pdf=path.join(root,"source.pdf");await writeFile(pdf,"%PDF-e2e");const output=path.join(root,"out");const config=path.join(root,"config.json");await writeFile(config,JSON.stringify({schemaVersion:2,research:{policy:{allowExternalFulltextUpload:true}}}));setEnv(t,{HOME:root,PI_SCHOLAR_OUTPUT_DIR:output,PI_SCHOLAR_CONFIG:config,MINERU_API_TOKEN:"E2E-SECRET",MINERU_POLL_INITIAL_MS:"100",MINERU_POLL_MAX_MS:"100",MINERU_MAX_ATTEMPTS:"4"});const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;});const requests:{url:string;method:string}[]=[];let polls=0;const zip=archive("# Heading\n\nFormula $E=mc^2$.\n\n|A|B|\n|-|-|\n|1|2|\n\n![Figure](images/plot.png)\nFigure 1: caption\n",{"images/plot.png":"PNG"});globalThis.fetch=async(input,init={})=>{const url=new URL(String(input));const method=init.method??"GET";requests.push({url:String(url),method});const zotero=zoteroFixture(url,pdf);if(zotero)return zotero;if(url.pathname==="/api/v4/file-urls/batch")return json({code:0,data:{batch_id:"e2e-batch",file_urls:["https://upload.example/signed?secret=SIGNED"]}});if(url.hostname==="upload.example")return new Response(null,{status:200});if(url.pathname.includes("/extract-results/batch/")){polls++;return json({code:0,data:{extract_result:[polls===1?{state:"running"}:{state:"done",file_name:"paper.pdf",full_zip_url:"https://download.example/signed?secret=SIGNED",version:"2.5"}]}});}if(url.hostname==="download.example")return new Response(zip.buffer.slice(zip.byteOffset,zip.byteOffset+zip.byteLength) as ArrayBuffer,{status:200});throw new Error(`unexpected ${url}`);};
  const tool=tools().get("pi_scholar_parse");const updates:any[]=[];const result=await tool.execute("call",{key:"PARENT01",attachmentKey:"PDF00001",allowExternalUpload:true},undefined,(u:any)=>updates.push(u),{});assert.ok(updates.length>=4);assert.ok(Buffer.byteLength(result.content[0].text)<50*1024);assert.doesNotMatch(result.content[0].text,/E2E-SECRET|SIGNED|upload\.example|download\.example/);const summary=JSON.parse(result.content[0].text);assert.equal(summary.status,"done");assert.equal(summary.selectedAttachmentKey,"PDF00001");const markdown=await readFile(summary.markdownPath,"utf8");assert.doesNotMatch(markdown,/E2E-SECRET|SIGNED|source\.pdf|\.pi-scholar-/);const end=markdown.indexOf("\n---\n",4);const meta=YAML.parse(markdown.slice(4,end));assert.equal(meta.zotero,"zotero://select/library/items/PARENT01");assert.equal(meta.zotero_pdf,"zotero://open-pdf/library/items/PDF00001");assert.equal(meta.zotero_key,undefined);assert.equal(meta.authors,"Ada Lovelace");assert.equal(meta.pdf_sha256,undefined);assert.equal(meta.mineru_batch_id,undefined);assert.equal(meta.zotero_metadata,undefined);assert.match(markdown,/# Heading[\s\S]*E=mc\^2[\s\S]*\|A\|B\|[\s\S]*Figure 1: caption/);const image=markdown.match(/!\[Figure\]\(<([^>]+)>\)/)?.[1];assert.ok(image);await readFile(path.join(path.dirname(summary.markdownPath),image));const sidecar=JSON.parse(await readFile(summary.metadataPath,"utf8"));assert.equal(sidecar.zotero.selected_metadata.DOI,"10.1000/mock");assert.equal(sidecar.notes[0].note,"A note");assert.equal(sidecar.annotations[0].text,"finding");assert.equal(sidecar.attachments.length,2);assert.equal(sidecar.pdf.sha256.length,64);assert.equal(sidecar.mineru.batchId,"e2e-batch");assert.equal(requests.some(r=>r.url.includes("127.0.0.1:23119")&&r.method!=="GET"),false);assert.equal(requests.filter(r=>r.url.includes("extract-results")).length,2);
});

test("mocked failure E2E throws, preserves existing output, cleans partial work and stops polling",async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),"pi-scholar-e2e-fail-"));const pdf=path.join(root,"source.pdf");await writeFile(pdf,"%PDF-e2e");const output=path.join(root,"out");const config=path.join(root,"config.json");await writeFile(config,JSON.stringify({schemaVersion:2,research:{policy:{allowExternalFulltextUpload:true}}}));await import("node:fs/promises").then(fs=>fs.mkdir(output));const existing=path.join(output,"valid.md");await writeFile(existing,"existing valid parse");setEnv(t,{HOME:root,PI_SCHOLAR_OUTPUT_DIR:output,PI_SCHOLAR_CONFIG:config,MINERU_API_TOKEN:"FAIL-SECRET",MINERU_POLL_INITIAL_MS:"100",MINERU_POLL_MAX_MS:"100",MINERU_MAX_ATTEMPTS:"10"});const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;});let polls=0;globalThis.fetch=async(input)=>{const url=new URL(String(input));const zotero=zoteroFixture(url,pdf);if(zotero)return zotero;if(url.pathname.endsWith("/file-urls/batch"))return json({code:0,data:{batch_id:"failed-batch",file_urls:["https://upload.example/signed"]}});if(url.hostname==="upload.example")return new Response(null,{status:200});if(url.pathname.includes("extract-results")){polls++;return json({code:0,data:{extract_result:[{state:"failed",err_msg:"document rejected"}]}});}throw new Error(`unexpected ${url}`);};await assert.rejects(tools().get("pi_scholar_parse").execute("call",{key:"PARENT01",attachmentKey:"PDF00001",allowExternalUpload:true},undefined,()=>{},{}),/MinerU parse failed: document rejected/);assert.equal(polls,1);assert.equal(await readFile(existing,"utf8"),"existing valid parse");assert.deepEqual((await readdir(output)).sort(),["valid.md"]);
});

test("default external upload policy rejects before any MinerU request",async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),"pi-scholar-e2e-deny-"));const pdf=path.join(root,"source.pdf");await writeFile(pdf,"%PDF-e2e");const output=path.join(root,"out");setEnv(t,{HOME:root,PI_SCHOLAR_OUTPUT_DIR:output,MINERU_API_TOKEN:"DENY-SECRET"});const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;});let mineruRequests=0;globalThis.fetch=async input=>{const url=new URL(String(input));const zotero=zoteroFixture(url,pdf);if(zotero)return zotero;if(url.hostname==="upload.example"||url.pathname.includes("/api/v4/file-urls"))mineruRequests++;throw new Error(`unexpected ${url}`);};await assert.rejects(tools().get("pi_scholar_parse").execute("call",{key:"PARENT01",attachmentKey:"PDF00001",allowExternalUpload:true},undefined,()=>{},{}),/AUTH_REQUIRED|SOURCE_UNAVAILABLE/);assert.equal(mineruRequests,0);
});
