import { Type } from "typebox";
import { StringEnum } from "@earendil-works/pi-ai";
import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { loadConfig, type ScholarConfig } from "./config.js";
import { ZoteroClient } from "./zotero.js";
import { MinerUClient } from "./mineru.js";
import { normalizeArchive, publishPaper } from "./output.js";

const LIMIT_BYTES=50*1024,LIMIT_LINES=2000;
export function truncate(text: string): { text: string; truncated: boolean; bytes: number; lines: number } {
  const bytes = Buffer.byteLength(text), lines = text.split("\n").length;
  if (bytes <= LIMIT_BYTES && lines <= LIMIT_LINES) return { text, truncated: false, bytes, lines };
  // Reserve marker space and count its lines inside the advertised total limit.
  const source = text.split("\n");
  const output: string[] = [];
  let shownBytes = 0;
  for (const line of source.slice(0, LIMIT_LINES)) {
    const size = Buffer.byteLength(line) + (output.length ? 1 : 0);
    if (shownBytes + size > LIMIT_BYTES - 160) break;
    output.push(line); shownBytes += size;
  }
  const shown = output.length;
  return { text: output.join("\n") + `\n\n[Truncated: displayed ${shown}/${lines} lines and ${shownBytes}/${bytes} bytes. Refine the query or read a specific item.]`, truncated: true, bytes, lines };
}
const configFor = (ctx: ExtensionContext): ScholarConfig => loadConfig(process.env, ctx.cwd, ctx.isProjectTrusted?.() === true);
const zoteroFor = (c: ScholarConfig): ZoteroClient => new ZoteroClient({ baseUrl: c.zoteroBaseUrl, dataDir: c.zoteroDataDir, timeoutMs: c.zoteroTimeoutMs, maxItems: c.zoteroMaxItems });
const result=(value:unknown,details:Record<string,unknown>={})=>{const t=truncate(JSON.stringify(value,null,2));return{content:[{type:"text" as const,text:t.text}],details:{...details,truncated:t.truncated,totalBytes:t.bytes,totalLines:t.lines}};};
export function registerScholarTools(pi:ExtensionAPI):void{
  pi.registerTool({name:"zotero_collections",label:"Zotero Collections",description:"Read-only list, metadata read, or item listing for Zotero Desktop collections. GET requests to loopback only. Output is limited to 50KB/2000 lines.",promptSnippet:"List or read local Zotero collections and their items",promptGuidelines:["Use zotero_collections to inspect local Zotero collection names, keys, metadata, and top-level items without modifying Zotero."],parameters:Type.Object({action:StringEnum(["list","read","items"] as const),key:Type.Optional(Type.String({pattern:"^[A-Z0-9]{8}$"})),limit:Type.Optional(Type.Integer({minimum:1,maximum:5000}))}),async execute(_id,p,signal,_onUpdate,ctx){const c=configFor(ctx);const z=zoteroFor(c);if(p.action==="read"){if(!p.key)throw new Error("zotero_collections read requires key");return result(await z.getCollection(p.key,signal));}if(p.action==="items"){if(!p.key)throw new Error("zotero_collections items requires key");return result(await z.listCollectionItems(p.key,p.limit,signal));}return result(await z.listCollections(p.limit,signal));}});
  pi.registerTool({name:"zotero_search",label:"Zotero Search",description:"Search top-level items in the read-only Zotero Desktop Local API, optionally in a collection/type. Output is limited to 50KB/2000 lines.",promptSnippet:"Search the local Zotero library",promptGuidelines:["Use zotero_search to match online papers locally, preferring DOI and then normalized title/year."],parameters:Type.Object({query:Type.String({minLength:1,maxLength:1000}),collectionKey:Type.Optional(Type.String({pattern:"^[A-Z0-9]{8}$"})),itemType:Type.Optional(Type.String({minLength:1,maxLength:100})),limit:Type.Optional(Type.Integer({minimum:1,maximum:500}))}),async execute(_id,p,signal,_onUpdate,ctx){const c=configFor(ctx);const z=zoteroFor(c);return result(await z.searchItems(p.query,{...(p.collectionKey?{collectionKey:p.collectionKey}:{}),...(p.itemType?{itemType:p.itemType}:{}),...(p.limit?{limit:p.limit}:{})},signal));}});
  pi.registerTool({name:"zotero_item",label:"Zotero Item",description:"Read one raw Zotero item or its complete normalized Paper aggregate including notes, attachments, annotations, indexed-text availability and PDF location. Read-only; output limited to 50KB/2000 lines.",promptSnippet:"Read complete Zotero paper metadata and child content",promptGuidelines:["Use zotero_item with aggregate mode before analyzing or parsing a local paper."],parameters:Type.Object({key:Type.String({pattern:"^[A-Z0-9]{8}$"}),mode:StringEnum(["item","aggregate"] as const),attachmentKey:Type.Optional(Type.String({pattern:"^[A-Z0-9]{8}$"}))}),async execute(_id,p,signal,_onUpdate,ctx){const c=configFor(ctx);const z=zoteroFor(c);return result(p.mode==="item"?await z.getItem(p.key,signal):await z.getPaper(p.key,p.attachmentKey,signal));}});
  pi.registerTool({name:"pi_scholar_parse",label:"Parse Zotero PDF with MinerU",description:"Uploads one local Zotero PDF to MinerU's official API, polls, downloads safely, and atomically saves plain Markdown/assets. Network use may consume quota. Returns only a bounded path/hash/task summary; never secrets.",promptSnippet:"Parse a Zotero PDF into structured local Markdown and assets",promptGuidelines:["Use pi_scholar_parse only when structured full text or figures are needed and a current hash-matching parse is unavailable."],parameters:Type.Object({key:Type.String({pattern:"^[A-Z0-9]{8}$"}),attachmentKey:Type.Optional(Type.String({pattern:"^[A-Z0-9]{8}$"}))}),async execute(_id,p,signal,onUpdate,ctx){const c=configFor(ctx);if(!c.mineruToken)throw new Error("MinerU credentials missing: set MINERU_API_TOKEN and reload Pi");const z=zoteroFor(c);const paper=await z.getPaper(p.key,p.attachmentKey,signal);if(!paper.selectedPdf)throw new Error("Zotero item has no PDF attachment");if(!paper.selectedPdf.localPath)throw new Error("Selected Zotero PDF file location cannot be resolved; check Zotero file availability or ZOTERO_DATA_DIR");const mineru=new MinerUClient({token:c.mineruToken,timeoutMs:c.mineruTimeoutMs,initialPollMs:c.mineruPollInitialMs,maxPollMs:c.mineruPollMaxMs,maxAttempts:c.mineruMaxAttempts,language:c.mineruLanguage,enableFormula:c.mineruEnableFormula,enableTable:c.mineruEnableTable,isOcr:c.mineruIsOcr,modelVersion:c.mineruModelVersion});const run=await mineru.extract(paper.selectedPdf.localPath,signal,stage=>onUpdate?.({content:[{type:"text",text:`MinerU: ${stage}`}],details:{stage}}));const normalized=normalizeArchive(run.archive,"__ASSET_PREFIX__",signal,c.assetFilePrefix);const parsedAt=new Date().toISOString();const published=await publishPaper(c.outputDir,paper,normalized,{pdfSha256:run.pdfSha256,mineru:run.info,parsedAt},signal,{filenameSeparator:c.filenameSeparator,literaturesDirectory:c.literaturesDirectory,tagSpaceReplacement:c.tagSpaceReplacement});return result({status:"done",zoteroKey:paper.zoteroKey,selectedAttachmentKey:paper.selectedPdf.key,...published});}});
}
